# ENV FOLDERS
DEV_FOLDER = "sql/dev/"
PROD_FOLDER = "sql/prod/"

# SQL FILES
GET_EXISTING_NETWORKS_SQL = "get_existing_networks.sql"
GET_ORPHAN_NETWORKS_SQL = "get_orphan_networks.sql"
DELETE_ORPHAN_NETWORKS_SQL = "delete_orphan_networks.sql"

# SERVICES URL
HTTP_PROTOCOL = "http://"
API_VERSION = "/v1"

STUDY_SERVER_URL = HTTP_PROTOCOL + "localhost:5001" + API_VERSION
NETWORK_STORE_SERVER_URL = HTTP_PROTOCOL + "localhost:8080" + API_VERSION
DIRECTORY_SERVER_URL = HTTP_PROTOCOL + "localhost:5026" + API_VERSION
ACTIONS_SERVER_URL = HTTP_PROTOCOL + "localhost:5022" + API_VERSION
FILTER_SERVER_URL = HTTP_PROTOCOL + "localhost:5027" + API_VERSION

LOADFLOW_SERVER_URL = HTTP_PROTOCOL + "localhost:5008" + API_VERSION
DYNAMIC_SIMULATION_SERVER_URL = HTTP_PROTOCOL + "localhost:5032" + API_VERSION
SECURITY_ANALYSIS_SERVER_URL = HTTP_PROTOCOL + "localhost:5023" + API_VERSION
SENSITIVITY_ANALYSIS_SERVER_URL = HTTP_PROTOCOL + "localhost:5030" + API_VERSION
SHORTCIRCUIT_SERVER_URL = HTTP_PROTOCOL + "localhost:5031" + API_VERSION
VOLTAGE_INIT_SERVER_URL = HTTP_PROTOCOL + "localhost:5038" + API_VERSION

# PATHS
GET_STUDIES = STUDY_SERVER_URL + "/supervision/studies"

GET_NETWORKS = NETWORK_STORE_SERVER_URL + "/networks"
DELETE_NETWORKS = NETWORK_STORE_SERVER_URL + "/networks"

GET_DIRECTORY_ELEMENTS = DIRECTORY_SERVER_URL + "/supervision/elements"

GET_CONTINGENCY_LISTS = ACTIONS_SERVER_URL + "/contingency-lists"
DELETE_CONTINGENCY_LISTS = ACTIONS_SERVER_URL + "/contingency-lists"

GET_FILTERS = FILTER_SERVER_URL + "/filters"
DELETE_FILTERS = FILTER_SERVER_URL + "/filters"

GET_LOADFLOW_RESULTS_COUNT = LOADFLOW_SERVER_URL + "/supervision/results-count"
GET_DYNAMIC_SIMULATION_RESULTS_COUNT = DYNAMIC_SIMULATION_SERVER_URL + "/supervision/results-count"
GET_SECURITY_ANALYSIS_RESULTS_COUNT = SECURITY_ANALYSIS_SERVER_URL + "/supervision/results-count"
GET_SENSITIVITY_ANALYSIS_RESULTS_COUNT = SENSITIVITY_ANALYSIS_SERVER_URL + "/supervision/results-count"
GET_SHORTCIRCUIT_RESULTS_COUNT = SHORTCIRCUIT_SERVER_URL + "/supervision/results-count"
GET_VOLTAGE_INIT_RESULTS_COUNT = VOLTAGE_INIT_SERVER_URL + "/supervision/results-count"

DELETE_STUDY_LOADFLOW_RESULTS = STUDY_SERVER_URL + "/supervision/loadflow/results"
DELETE_STUDY_DYNAMIC_SIMULATION_RESULTS = STUDY_SERVER_URL + "/supervision/dynamic-simulation/results"
DELETE_STUDY_SECURITY_ANALYSIS_RESULTS = STUDY_SERVER_URL + "/supervision/security-analysis/results"
DELETE_STUDY_SENSITIVITY_ANALYSIS_RESULTS = STUDY_SERVER_URL + "/supervision/sensitivity-analysis/results"
DELETE_STUDY_SHORTCIRCUIT_RESULTS = STUDY_SERVER_URL + "/supervision/shortcircuit/results"
DELETE_STUDY_VOLTAGE_INIT_RESULTS = STUDY_SERVER_URL + "/supervision/voltage-init/results"
