# ENV FOLDERS
DEV_FOLDER="sql/dev/"
PROD_FOLDER="sql/prod/"

# SQL FILES
GET_EXISTING_NETWORKS_SQL="get_existing_networks.sql"
GET_ORPHAN_NETWORKS_SQL="get_orphan_networks.sql"
DELETE_ORPHAN_NETWORKS_SQL="delete_orphan_networks.sql"

# SERVICES URL
HTTP_PROTOCOL="http://"
API_VERSION="/v1"

STUDY_SERVER_URL=HTTP_PROTOCOL + "localhost:5001" + API_VERSION
NETWORK_STORE_SERVER_URL=HTTP_PROTOCOL + "localhost:8080" + API_VERSION
DIRECTORY_SERVER_URL=HTTP_PROTOCOL + "localhost:5026" + API_VERSION
ACTIONS_SERVER_URL=HTTP_PROTOCOL + "localhost:5022" + API_VERSION
FILTER_SERVER_URL=HTTP_PROTOCOL + "localhost:5027" + API_VERSION

# PATHS
GET_STUDIES=STUDY_SERVER_URL + "/supervision/studies"

GET_NETWORKS=NETWORK_STORE_SERVER_URL + "/networks"
DELETE_NETWORKS=NETWORK_STORE_SERVER_URL + "/networks"

GET_DIRECTORY_ELEMENTS=DIRECTORY_SERVER_URL + "/supervision/elements"

GET_CONTINGENCY_LISTS=ACTIONS_SERVER_URL + "/contingency-lists"
DELETE_CONTINGENCY_LISTS=ACTIONS_SERVER_URL + "/contingency-lists"

GET_FILTERS=FILTER_SERVER_URL + "/filters"
DELETE_FILTERS=FILTER_SERVER_URL + "/filters"