{
 "title": "External services supervision",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values({service=\"kube-prometheus-stack-kubelet\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"rabbitmq\", endpoint=\"metrics\"} OR on() vector(0)",
     "legendFormat": "rabbitmq"
    },
    {
     "expr": "up{service=\"elasticsearch\", endpoint=\"metrics\"} OR on() vector(0)",
     "legendFormat": "elasticsearch"
    },
    {
     "expr": "up{service=\"postgres\", endpoint=\"metrics\"} OR on() vector(0)",
     "legendFormat": "postgres"
    }
   ]
  },
  {
   "title": "Disk space used (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes)/node_filesystem_size_bytes",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "1-kubelet_volume_stats_available_bytes{service=\"$service\"}/kubelet_volume_stats_capacity_bytes{service=\"$service\"}",
     "legendFormat": "case-directory ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Detailed status infos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "RabbitMQ status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "up{service=\"rabbitmq\", endpoint=\"metrics\"} OR on() vector(0)",
       "legendFormat": "rabbitmq"
      }
     ]
    },
    {
     "title": "ElasticSearch status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "up{service=\"elasticsearch\", endpoint=\"metrics\"} OR on() vector(0)",
       "legendFormat": "elasticsearch"
      }
     ]
    },
    {
     "title": "Postgres status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "up{service=\"postgres\", endpoint=\"metrics\"} OR on() vector(0)",
       "legendFormat": "postgres"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed disk space infos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space used (%)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes)/node_filesystem_size_bytes",
       "legendFormat": "{{mountpoint}}"
      },
      {
       "expr": "1-kubelet_volume_stats_available_bytes{service=\"$service\"}/kubelet_volume_stats_capacity_bytes{service=\"$service\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Disk space used",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes - node_filesystem_avail_bytes",
       "legendFormat": "{{mountpoint}}"
      },
      {
       "expr": "kubelet_volume_stats_capacity_bytes{service=\"$service\"}-kubelet_volume_stats_available_bytes{service=\"$service\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Disk space available",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "node_filesystem_avail_bytes", "legendFormat": "{{mountpoint}} - Available" },
      {
       "expr": "kubelet_volume_stats_available_bytes{service=\"$service\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}