{
 "title": "Application pools",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Network Diagram Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Diagram Generation - Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "app_diagram_tasks_pool_pending", "legendFormat": "{{pod}}-{{type}}" }
   ]
  },
  {
   "title": "Network Diagram Generation - Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "app_diagram_tasks_pool_current", "legendFormat": "{{pod}}-{{type}}" }
   ]
  },
  { "title": "Network Modification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Modification - Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "app_network_modification_tasks_pool_pending",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Network Modification - Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "app_network_modification_tasks_pool_current",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  { "title": "Network Conversion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network Conversion - Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "app_conversion_tasks_pool_pending",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Network Conversion - Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "app_conversion_tasks_pool_current",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  { "title": "Geo Data Fetch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Geo Data Fetch - Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "app_geo_data_tasks_pool_pending",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Geo Data Fetch - Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "app_geo_data_tasks_pool_current",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  }
 ]
}