{
 "title": "Cases (import & export)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Case processing reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Case import time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_case_import_seconds_max) by (storage_type)",
     "legendFormat": "{{storage_type}}"
    }
   ]
  },
  {
   "title": "Case writing time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_case_writing_seconds_max) by (storage_type)",
     "legendFormat": "{{storage_type}}"
    }
   ]
  },
  {
   "title": "Case export time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{method='GET', uri='/v1/cases/{caseUuid}'})"
    }
   ]
  },
  {
   "title": "Case size (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(app_case_import_size_max) by (storage_type)",
     "legendFormat": "{{storage_type}}"
    }
   ]
  },
  {
   "title": "Case exist time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_case_is_exist_seconds_max) by (storage_type)",
     "legendFormat": "{{storage_type}}"
    }
   ]
  }
 ]
}