{
 "title": "Network storage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "General metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Get one equipment (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_get_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Get all equipments (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_get_all_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}} "
      }
     ]
    },
    {
     "title": "Create all equipments (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_create_all_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Remove all equipments (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_remove_all_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Update all equipments (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_update_all_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Clone network (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_clone_seconds_max)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Normalized metrics (per equipment max)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "panels": [
    {
     "title": "Get all equipments (per equipment max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_get_all_per_resource_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Remove all equipments (per equipment max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_remove_all_per_resource_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Create all equipments (per equipment max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_create_all_per_resource_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    },
    {
     "title": "Clone network (per variant max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_clone_per_variant_seconds_max)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update all equipments (per equipment max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_update_all_per_resource_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extensions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "panels": [
    {
     "title": "Get all extensions (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_get_all_extensions_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Limits groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "panels": [
    {
     "title": "Get all limits groups (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_get_all_limits_groups_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}} "
      }
     ]
    },
    {
     "title": "Get all selected limits groups (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(app_network_store_server_get_all_limits_groups_selected_seconds_max) by (resource_type)",
       "legendFormat": "{{resource_type}} "
      }
     ]
    }
   ]
  }
 ]
}