{
 "title": "Network modifications",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Network modification reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incremental modification time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum  by (modification_type) (app_network_modification_apply_seconds_max{error=\"none\"})",
     "legendFormat": "{{modification_type}}"
    }
   ]
  },
  {
   "title": "Incremental modification rate with success (count/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(app_network_modification_apply_seconds_count{error='none'}[$__rate_interval])) * 60",
     "legendFormat": "{{modification_type}}"
    }
   ]
  },
  {
   "title": "Network consume event time (max)",
   "type": "timeseries",
   "description": "From message received to response sent.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "app_network_modification_consume_build_message_seconds_max{error=\"none\"}"
    }
   ]
  },
  {
   "title": "Network consume event rate with success (count/min)",
   "type": "timeseries",
   "description": "From message received to response sent.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(app_network_modification_consume_build_message_seconds_count{error='none'}[$__rate_interval])) * 60"
    }
   ]
  },
  {
   "title": "Network variant build time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "app_network_modification_build_seconds_max{error=\"none\"}"
    }
   ]
  },
  {
   "title": "Network build rate with success (count/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(app_network_modification_build_seconds_count{error='none'}[$__rate_interval])) * 60"
    }
   ]
  },
  {
   "title": "Queued build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages_ready{queue=\"build.run.buildGroup\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}