{
 "title": "Kubernetes resource monitoring",
 "description": "The dashboard offers a simple view of the resource consumption of the deployed pods and their impact on the cluster. The outline of requests and limits for each pod and their totals can be used as a tool to determine appropriate resource quotas for your cluster.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pods Restarted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(node_namespace_pod_container:container_memory_rss{image!=\"\", container_name!=\"POD\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "max(node_namespace_pod_container:container_memory_rss{name!=\"\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (pod)"
    },
    {
     "expr": "max(kube_pod_info) by (pod,namespace,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{image!=\"\", container_name!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}