{
 "title": "Total CPU usage",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "% cpu usage / requests par pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[$__interval:15s])\n/\non(namespace,pod,container)\nkube_pod_container_resource_requests{resource=\"cpu\"} * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% cpu usage / limits par pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[$__interval:15s])\n/\non(namespace,pod,container)\nkube_pod_container_resource_limits{resource=\"cpu\"} * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% cpu usage / requests par image",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time (sum by (image) (irate(container_cpu_usage_seconds_total{image!=\"\"}[90s]))[$__interval:15s]) / sum by (image) (kube_pod_container_resource_requests{resource=\"cpu\"}\n* on(namespace,pod,container)\ngroup_left(image)\nkube_pod_container_info) * 100"
    }
   ]
  },
  {
   "title": "% cpu usage / limits par image",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time (sum by (image) (irate(container_cpu_usage_seconds_total{image!=\"\"}[90s]))[$__interval:15s]) / sum by (image) (kube_pod_container_resource_limits{resource=\"cpu\"}\n* on(namespace,pod,container)\ngroup_left(image)\nkube_pod_container_info) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% cpu usage / request by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max_over_time (sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)[$__interval:15s])\n/\non(namespace)\nnamespace_cpu:kube_pod_container_resource_requests:sum * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% cpu usage / limits by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max_over_time (sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)[$__interval:15s])\n/\non(namespace)\nnamespace_cpu:kube_pod_container_resource_limits:sum * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)[$__interval:15s])",
     "legendFormat": "__auto"
    },
    {
     "expr": "namespace_cpu:kube_pod_container_resource_requests:sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "namespace_cpu:kube_pod_container_resource_limits:sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "TODO ajouter autres vues aggrégé du système global, vérifier la relation avec la vue k8s resources monitoring\n\nTODO j'ai ajouté une version avec max_over_time et subqueries pour éviter que le pic soit caché quand on dezoom beaucoup (downsampling)"
   }
  }
 ]
}