{
 "title": "Server load",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of HTTP requests on server (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(http_server_requests_seconds_count{exception=\"none\", uri!~\".*actuator.*\", job=~\".*$job.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of HTTP requests on server (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod, uri, method) (rate(http_server_requests_seconds_count{job=~\".*$job.*\", exception=\"none\", uri!~\".*actuator.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests on server (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod, uri, method) (delta(http_server_requests_seconds_sum{job=~\".*$job.*\", uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of client HTTP requests (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pod, uri, method) (delta(http_client_requests_seconds_count{job=~\".*$job.*\", uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in client HTTP requests on server (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pod, uri, method) (delta(http_client_requests_seconds_sum{job=~\".*$job.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rabbit message consume on server (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(pod) (delta(rabbitmq_consumed_total{job=~\".*$job.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}