{
 "title": "Top requests",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Top 100 Longest Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(100, max (max_over_time(http_server_requests_seconds_max{job!=\"gateway\"}[$__range])) by(uri, job, outcome, method))"
    },
    {
     "expr": "sum (increase(http_server_requests_seconds_count{job!=\"gateway\"}[$__range])) by(uri, outcome, method)"
    },
    {
     "expr": "sum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_sum{job!=\"gateway\"}[$__range])\n)\n/ \nsum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_count{job!=\"gateway\"}[$__range])\n) "
    }
   ]
  },
  {
   "title": "Requests in error",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (method, uri, exception, status, job) (\n        increase(\n            http_server_requests_seconds_count{job!=\"gateway\", uri!~\"/actuator/.*\", status=~\"5..|400|499\"}[$__range]\n        )\n    ) > 0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)"
    }
   ]
  },
  {
   "title": "Requests in error over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "label_replace(\n        changes(\n            http_server_requests_seconds_count{job!=\"gateway\", uri!~\"/actuator/.*\", status=~\"5..|400|499\"}[$__rate_interval]\n        )>0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)",
     "legendFormat": "method={{method}}, uri={{uri}}, exception={{exception}}, status={{status}}, job={{job}}"
    }
   ]
  }
 ]
}