name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@5e13dcb03778dc9a47bd0adbd84c48392b32cd46
    with:
      dockerImage: gridsuite/admin-tools
      dockerUsername: gridsuiteci
      dockerRoUsername: rogridsuiteci
      eventType: admin_tools_updated
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      docker-ro-token: ${{ secrets.DOCKERHUB_RO_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
