name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-base-docker-image-generic.yml@0c71f00e40f49d9bbfc59acb821387e0751ab4d2
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      dockerImage: gridsuite/admin-tools
      dockerUsername: gridsuiteci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      githubappPrivateKey: ${{ secrets.GRIDSUITE_ACTIONS_SECRET }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
