name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-base-docker-image-generic.yml@69b162754c0728d9aeb2ea568eaf47f28f60fafb
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      dockerImage: gridsuite/admin-tools
      dockerUsername: gridsuiteci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
